
---

- hosts: all
  become: true
  tasks:

  - name: install apache and php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: copy static file for deployment
    copy:
      src: hello-world.html
      dest: /var/www/html/index.html
      owner: joaquin
      group: joaquin
      mode: 0644
